improved things

diff --git a/shebang/gif b/shebang/gif
--- a/shebang/gif
+++ b/shebang/gif
@@ -1,32 +1,34 @@
 #!/usr/bin/env bash
-if (( $# == 0 )); then
-    >&2 echo "Expected a video file as an argument but didn't get one"
-    exit 1
-elif (( $# > 1 )); then
-    >&2 echo "Expected only one argument (a video file) but got multiple"
-    exit 2
-elif [ ! -f "$1" ]; then
-    >&2 echo "$1 is not a valid file"
-    exit 3
-elif ! is_command ffmpeg; then
-    >&2 echo "ffmpeg is not installed"
+if ! is_command ffmpeg; then
+    >&2 echo 'gif requires ffmpeg'
     exit 4
 elif ! is_command gifski; then
-    >&2 echo "gifski (https://gif.ski) is not installed"
+    >&2 echo 'gif requires gifski (https://gif.ski)'
     if is_command cargo; then
-        >&2 echo "Perhaps do:"
-        >&2 echo "cargo install gifski"
+        >&2 echo 'Perhaps do:'
+        >&2 echo 'cargo install gifski'
         exit 5
     fi
     exit 6
 elif ! is_command fps; then
     >&2 echo "fps isn't a command. Did you just download this script by itself? Fair enough, but it does depend on the fps script too."
     exit 7
-else
-    fps_variable="$(fps $1)"
-    timestamp="$(date +%s)"
-    dir="/tmp/gif$timestamp"
-    mkdir "$dir"
-    ffmpeg -i "$1" "${dir}/frame%04d.png"
-    gifski -o "${timestap}.gif" --fps ${fps_variable} ${dir}/frame*.png
+elif (( $# == 0 )); then
+    >&2 echo "Expected a video file as an argument but didn't get one"
+    exit 1
+elif (( $# > 1 )); then
+    >&2 echo 'Expected only one argument (a video file) but got multiple'
+    exit 2
+elif [ ! -f "$1" ]; then
+    >&2 echo "$1 is not a valid file"
+    exit 3
 fi
+fps_variable="$(fps $1)"
+timestamp="$(date +%s)"
+dir="/tmp/gif$timestamp"
+if ! mkdir "$dir"
+    >&2 echo "Failed to mkdir $dir"
+    exit 8
+fi
+ffmpeg -i "$1" "${dir}/frame%04d.png"
+gifski -o "${timestap}.gif" --fps ${fps_variable} ${dir}/frame*.png
